<a href="https://colab.research.google.com/github/kanakesh2006/60hours-of-Machine-Learning-Part-1/blob/main/3.1.%20Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy - Numerical Python

## Advantages of Numpy Arrays:
1.    Allows several Mathematical Operations
1.    Faster Operations

In [3]:
import numpy as np

### List vs Numpy - Time Taken

In [4]:
from time import process_time

Time taken by List

In [5]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0010391740000006422


Time taken by Numpy Array

In [6]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00018872600000019446


### Numpy Arrays

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# 1D array
a = np.array([1,2,3,4])
print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [9]:
# 2D array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [10]:
# 3D array
c = np.array()
print(c)
print(c.shape)

TypeError: array() missing required argument 'object' (pos 0)

In [12]:
d = np.array([(1,2,3,4),(3,4,5,6)], dtype=float)
print(d)

[[1. 2. 3. 4.]
 [3. 4. 5. 6.]]


Initial placeholders in numpy arrays

In [13]:
# numpy array of zeroes
x = np.zeros((3,5))
print(x)
print(x.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(3, 5)


In [14]:
# numpy array of ones
y = np.ones((3,5))
print(y)
print(y.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(3, 5)


In [15]:
# numpy array of specific number
z = np.full((3,5), 93)
print(z)
print(z.shape)

[[93 93 93 93 93]
 [93 93 93 93 93]
 [93 93 93 93 93]]
(3, 5)


In [16]:
# numpy array of identity matrix
p = np.eye(4)
print(p)
print(p.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [17]:
# numpy array of random values
l = np.random.random((3,5))
print(l)
print(l.shape)

[[0.27661701 0.12586337 0.27419476 0.11409266 0.46207895]
 [0.96740769 0.96401739 0.17856751 0.54651185 0.8278568 ]
 [0.65104284 0.09020187 0.92551569 0.85967052 0.36967591]]
(3, 5)


In [18]:
# numpy array of random integer values within a specific range
m = np.random.randint(10,100, (3,5))
print(m)
print(m.shape)

[[95 47 63 88 60]
 [43 31 84 74 17]
 [18 84 44 53 88]]
(3, 5)


In [19]:
# numpy array of evenly spaced values with specific number of values
n = np.linspace(10,30,2)
print(n)
print(n.shape)

[10. 30.]
(2,)


In [20]:
# numpy array of evenly spaced values with specific steps/intervals
o = np.arange(10,30,2)
print(o)
print(o.shape)

[10 12 14 16 18 20 22 24 26 28]
(10,)


In [25]:
# convert a list to a numpy array
array = [10,20,30,40,50]
list2np = np.asarray(array)
print(list2np)
print(type(list2np))
print(list2np.shape)

[10 20 30 40 50]
<class 'numpy.ndarray'>
(5,)


Analysing a Numpy array

In [26]:
arr = np.random.randint(10,90,(5,5))
print(arr)

[[61 73 10 39 67]
 [26 36 40 27 12]
 [49 19 29 54 80]
 [29 53 38 15 16]
 [68 25 21 20 83]]


In [28]:
# no of dimensions
print(arr.ndim)

2


In [29]:
# what are the dimensions
print(arr.shape)

(5, 5)


In [30]:
# no of elements
print(arr.size)

25


In [31]:
# data type of elements
print(arr.dtype)

int64


Mathematical Operations on Numpy Arrays

In [33]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,0]
print(list1 + list2) # Concatenation

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


In [36]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(10,20,(3,3))
print(arr1)
print(arr2)
print("-----------------------------------")
print(arr1 + arr2) # element-wise addition
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[0 6 3]
 [5 4 3]
 [6 8 0]]
[[15 12 14]
 [11 12 17]
 [16 17 14]]
-----------------------------------
[[15 18 17]
 [16 16 20]
 [22 25 14]]
[[-15  -6 -11]
 [ -6  -8 -14]
 [-10  -9 -14]]
[[  0  72  42]
 [ 55  48  51]
 [ 96 136   0]]
[[0.         0.5        0.21428571]
 [0.45454545 0.33333333 0.17647059]
 [0.375      0.47058824 0.        ]]


In [37]:
print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))


[[15 18 17]
 [16 16 20]
 [22 25 14]]
[[-15  -6 -11]
 [ -6  -8 -14]
 [-10  -9 -14]]
[[  0  72  42]
 [ 55  48  51]
 [ 96 136   0]]
[[0.         0.5        0.21428571]
 [0.45454545 0.33333333 0.17647059]
 [0.375      0.47058824 0.        ]]


Array manipulation

In [38]:
# Transpose
array1 = np.random.randint(0,9,(2,3))

trans1 = np.transpose(array1)
print(trans1)
print(trans1.shape)

trans2 = array1.T
print(trans2)
print(trans2.shape)

[[2 6]
 [3 6]
 [7 3]]
(3, 2)
[[2 6]
 [3 6]
 [7 3]]
(3, 2)


In [41]:
# Reshape
array2 = np.random.randint(10,20,(2,3))

print(array2)
print(array2.shape)

print(array2.reshape(3,2))
print(array2.shape)

[[17 15 18]
 [15 19 14]]
(2, 3)
[[17 15]
 [18 15]
 [19 14]]
(2, 3)
